---

# This concatenates the zabbix_templates list obtained from group_vars with
#   the zabbix_templates_extra list obtained from individual host_vars.
- name: ZABBIX | Assemble template list
  set_fact:
    zabbix_templates: "{{ zabbix_templates + zabbix_templates_extra }}"
  when: zabbix_templates_extra is defined

# Do the same thing for the host groups.
- name: ZABBIX | Assemble host groups list
  set_fact:
    zabbix_host_group_membership: "{{ zabbix_host_group_membership + zabbix_host_group_membership_extra }}"
  when: zabbix_host_group_membership_extra is defined

- name: ZABBIX | DEBUG
  debug:
    var: zabbix_templates
  when: debug_mode

# USE PYTHON 3 FOR THIS
- name: ZABBIX | Host information updated on Zabbix server
  become: false
  delegate_to: localhost
  community.zabbix.zabbix_host:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_service_account_name }}"
    login_password: "{{ zabbix_service_account_password }}"
    host_name: "{{ hostname }}"
    validate_certs: "{{ zabbix_validate_certs }}"
    visible_name: "{{ zabbix_host_visible_name }}"
    description: "{{ notes | default('This host requires a description!') }}"
    host_groups: "{{ zabbix_host_group_membership | default(omit) }}"
    link_templates: "{{ zabbix_templates }}"
    tls_connect: 2
    tls_accept: 2
    tls_psk: "{{ zabbix_psk }}"
    tls_psk_identity: "{{ zabbix_tlspskidentity }}"
    proxy: "{{ zabbix_server_or_proxy_name | default(omit) }}"
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        dns: "{{ hostname }}"
        port: "10050"
    status: enabled
    state: present
