---

- name: MAIN | Windows uninstall tasks imported
  ansible.builtin.import_tasks: windows-uninstall.yml
  when:
    - uninstall
    - ansible_facts.os_family == "Windows"

- name: MAIN | Windows install tasks imported
  ansible.builtin.import_tasks: windows-install.yml
  tags: zab_agent_install
  when:
    - not uninstall
    - ansible_facts.os_family == "Windows"

- name: MAIN | Linux install tasks imported
  become: true
  ansible.builtin.import_tasks: linux-install.yml
  tags: zab_agent_install
  when:
    - not uninstall
    - ansible_facts.os_family != "Windows"
    - ansible_facts.system == "Linux"

- name: MAIN | FreeBSD install tasks imported
  become: true
  ansible.builtin.import_tasks: freebsd-install.yml
  tags: zab_agent_install
  when:
    - not uninstall
    - ansible_facts.os_family != "Windows"
    - ansible_facts.system == "FreeBSD"

- name: MAIN | Flush handlers
  meta: flush_handlers

- name: MAIN | Configure tasks imported
  ansible.builtin.import_tasks: configure.yml
  tags: zab_agent_configure
  when: not uninstall
