---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: centos-host
    box: centos/7
    memory: 1024
    cpus: 1
  - name: ubuntu-host
    box: ubuntu/groovy64
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  inventory:
    host_vars:
      centos-host:
        hostname: centos-host
      ubuntu-host:
        hostname: ubuntu-host
verifier:
  name: ansible
