---

- name: HANDLERS | Zabbix agent restarted (Windows)
  ansible.windows.win_service:
    name: Zabbix Agent
    state: restarted
    start_mode: auto
  listen: restart-zabbix-agent-windows

- name: HANDLERS | Zabbix agent restarted (Linux)
  ansible.builtin.service:
    name: "{{ zabbix_agent_service }}"
    state: restarted
    enabled: true
  listen: restart-zabbix-agent-linux

- name: HANDLERS | Zabbix agent 2 restarted (Linux)
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: true
  listen: restart-zabbix-agent2-linux

- name: HANDLERS | Zabbix agent restarted (FreeBSD)
  ansible.builtin.service:
    name: zabbix_agentd
    state: restarted
    enabled: true
  listen: restart-zabbix-agent-freebsd
