---

- name: HANDLERS | Zabbix agent restarted (Windows)
  ansible.windows.win_service:
    name: Zabbix Agent
    state: restarted
    start_mode: auto
  listen: restart-zabbix-agent-windows

- name: HANDLERS | Zabbix agent restarted (Linux)
  ansible.builtin.service:
    name: "{{ zabbix_agent_service }}"
    state: restarted
    enabled: true
  listen: restart-zabbix-agent-linux
